version: '3'

services:
    php:
        build: ./docker
        volumes:
            - ./docker/php.ini:/usr/local/etc/php/php.ini:ro
            - ./:/app
        working_dir: /app

    webserver:
        image: nginx
        depends_on:
            - php
        volumes:
            - ./:/app
            - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
        ports:
            - 8888:80

    composer:
        image: composer
        volumes:
            - ./:/app
        working_dir: /app
        command: install
